export enum ComponentIdConstants {
    HEADER="HEADER",
    WONDERLAND="WONDERLAND",
    NEWLOCATIONS="NEWLOCATIONS",
    TEAMBUILDING="TEAMBUILDING",
    TRUSTEDBY="TRUSTEDBY",
    SUPERCOMPANIES="SUPERCOMPANIES",
    CAFE="CAFE",
    CATEGORYSECTION="CATEGORYSECTION",
    WORKINGSPACE="WORKINGSPACE"

}
